### ISSUE TITLE
Thunderstore package

### ISSUE THREAD

**Issue by MythicManiac** [LongParsnip/Mod-Cloud#1]
Hey, I figured this is probably the best place to contact you; if you're wondering the reasoning for the disappearance of the Thunderstore package, you can see some feedback with a direct link as long as you're signed in: <https://valheim.thunderstore.io/package/GamefaceGamers/Mod_Sync/>

**Comment by LP-Atkins** [comment]
Thanks Mythic, I thought as much. I couldn't find a ToS for thunderstore because apparently they don't have one so I ummed and ahhed about it for over a year before finally deciding to just do it (as when I released it on Nexus there was a lot of interest from members that found it useful).

Unfortunately there seems to be no platform for these grey area utilities that provide functionality you just can't get from a mod manager when you are dealing with a multiplayer environment.

**Comment by MythicManiac** [comment]
> Unfortunately there seems to be no platform for these grey area utilities 

Yeah that seems to be the case. We try to remain as open as possible with Thunderstore while also respecting the needs and wishes of the creators using our platform.

This tool was probably the biggest gray area we've had to look into so far, but ultimately the lack of integration with the ecosystem would make it unreliable, which made it easy to rule as offtopic/potentially harmful to the ecosystem, and removed with similar grounds as to why we'd remove spam or other harmful content.

We're quite pragmatic about the guarantees offered by the ecosystem (such as package version immutability, filesystem safe unique package IDs, enforced ID namespacing, etc.) and the goals we're striving towards (reliability being a key factor), so you can probably understand how something that operates outside of that entirely (in this case OneDrive) goes against that.

I can acknowledge the problem this was aimed at solving does exist, and coincidentally we're also working on providing solutions to it. Our tooling however won't be targeting other ecosystems (e.g. nexusmods) at least early on given that it loses some of the guarantees I mentioned earlier, but perhaps we can implement some form of a translation layer later on. Proper versioning, standardized packaging, immutability guarantees, and global filesystem safe package IDs are some of the the key features missing from most alternative ecosystems, which is why we don't feel particularly bad about drawing the line there.

On that note, we wouldn't have nearly as big of a problem with something that operates outside of our ecosystem if the way it operates would be aligned with what we're striving to build. OneDrive integration doesn't quite make the cut here unfortunately.

If you're interested in the tooling development I mentioned, I'd encourage you to join the Thunderstore [Discord server](https://discord.gg/UWpWhjZken) if you haven't already. We're aiming to get a pre-release of a server side mod manager out by the end of this month, and I'd imagine that might be helpful for this use case as well.

I'd also like to say it's great to have community participation like this exist, even if it's not aligned with our goals right now. this gave us a good opportunity to think about where we draw the line and it never hurts to have multiple solutions around in case one stops working.

**Comment by LP-Atkins** [comment]
Thanks for the feedback Mythic, that was a really well thought out response.

Glad to hear you guys are looking into the server side of modding as well, mod managers are fantastic for single player but things get messy when dealing with multiplayer so a proper in house solution I am excited for.
